name: shelf_mvc
description: An shelf package to render pages according the mvc principles.
version: 0.0.1
author: Joris Hermans <hermansj@gmail.com>
homepage: https://github.com/jorishermans/shelf_mvc
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  shelf: ">=0.6.0 <0.7.0"
  uri: "^0.10.0"
  mustache: "^0.2.5"
  http_server: ">=0.9.0 <0.10.0"
  logging: ">=0.9.0 <0.10.0"
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
